OPENAI_API_KEY = "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"
QDRANT_URL = "https://97d1f6e9-a2c9-4396-a58c-5807c7cc0a52.us-east4-0.gcp.cloud.qdrant.io/"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.Wlzi6SDqW_yeNDWS9YLsxMjJU30t7PQSA9N8wyxmrUQ"
